# Generated by Django 5.2.4 on 2025-07-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories',
            name='activity',
            field=models.CharField(choices=[('BMR (BASE METABOLIC RATE)', 'BMR'), ('Sedentary', 'Sedentary'), ('Light', 'Light'), ('Moderate', 'Moderate'), ('Active', 'Active')], max_length=30),
        ),
    ]
