# Generated by Django 5.2.4 on 2025-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_alter_calories_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories',
            name='activity',
            field=models.CharField(choices=[('BMR', 'BMR (BASE METABOLIC RATE)'), ('Sedentary', 'Sedentary: little or no exercise'), ('Light', 'Light: exercise 1-3 times/week'), ('Moderate', 'Moderate: exercise 4-5 times/week'), ('Active', 'Active: exercise 5-7 times/week')], max_length=30),
        ),
    ]
