# Generated by Django 5.2.4 on 2025-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Stretching', 'Stretching'), ('HIIT', 'HIIT'), ('Other', 'Other')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
            ],
        ),
    ]
